### ISSUE TITLE
Add support for Legion bodyguards

### ISSUE THREAD

**Issue by Sharparam** [SharpWoW/LibBodyguard-1.0#4]
:information_source: **This issue will be continously updated as new information is gathered.**
## TODO
- [x] Detect if a follower is assigned as a "Combat Ally"
- [x] Detect if said "Combat Ally" is a proper bodyguard (and not just providing some spell)
- [x] Update library to handle both WoD and Legion bodyguards
## Analysis

The library should support Legion bodyguards.

This might require some reworking in how bodyguards are handled, to account for bodyguards from different expansions (WoD and Legion). Or perhaps there can be a seamless transition?

On my Horde Druid, out of the visible followers, only one can be a bodyguard that follows you around in the world: Broll Bearmantle.

The output of `C_Garrison.GetFollowers()` gives this (trimmed to only show Broll Bearmantle):

``` lua
[3]={
  displayHeight=0.5,
  followerTypeID=4,
  zoneSupportSpellID=218603,
  iLevel=760,
  scale=0.60000002384186,
  classAtlas="GarrMission_ClassIcon-Druid-Feral",
  isTroop=false,
  displayIDs={
    [1]={
      followerPageScale=1,
      showWeapon=true,
      id=65529
    }
  },
  displayScale=1,
  status="Combat Ally",
  level=103,
  quality=1,
  portraitIconID=1360256,
  isFavorite=false,
  slotSoundKitID=67139,
  xp=702,
  className="Feral Druid",
  classSpec=112,
  isMaxLevel=false,
  name="Broll Bearmantle",
  followerID="0x00000000023CDF49",
  height=1.3500000238419,
  levelXP=800,
  isCollected=true,
  garrFollowerID=641
},
```

(The above table is inside the first table returned by the function.)

The entry `zoneSupportSpellID=218603` gives information on the "Combat Ally" spell for the follower. The output of `GetSpellInfo(218603)` is the following:

``` lua
[1]="Bodyguard",
[2]="",
[3]=571585,
[4]=0,
[5]=0,
[6]=40,
[7]=218603
```

~~:warning: **This should be tested to see if all Bodyguard followers share that same spell.** :warning:~~

@InvisiBilldotnet did some investigating and found the following bodyguard spells:

| Class | Spec | Follower | Spell |
| --- | --- | --- | --: |
| Death Knight | Blood | [Koltira Deathweaver](http://www.wowhead.com/champion=599) | [222365](http://www.wowhead.com/spell=222365) |
| Demon Hunter | Vengeance | [Belath Dawnblade](http://www.wowhead.com/champion=594) | [222964](http://www.wowhead.com/spell=222964) |
| Druid | Feral | [Broll Bearmantle](http://www.wowhead.com/champion=641) | [218603](http://www.wowhead.com/spell=218603) |
| Hunter | Survival | [Addie Fizzlebog](http://www.wowhead.com/champion=746) | [219995](http://www.wowhead.com/spell=219995) |
| Hunter | Survival | [Rexxar](http://www.wowhead.com/champion=743) | [220814](http://www.wowhead.com/spell=220814) |
| Mage | Fire | [Millhouse Manastorm](http://www.wowhead.com/champion=723) | [220212](http://www.wowhead.com/spell=220212) |
| Mage | Frost | [Archmage Modera](http://www.wowhead.com/champion=717) | [220125](http://www.wowhead.com/spell=220125) |
| Monk | Brewmaster | [Chen Stormstout](http://www.wowhead.com/champion=596) | [211945](http://www.wowhead.com/spell=211945) |
| Monk | Windwalker | [The Monkey King](http://www.wowhead.com/champion=602) | [212145](http://www.wowhead.com/spell=212145) |
| Paladin | Protection | [Vindicator Boros](http://www.wowhead.com/champion=479) | [221625](http://www.wowhead.com/spell=221625) |
| Paladin | Retribution | [Arator the Redeemer](http://www.wowhead.com/champion=758) | [221713](http://www.wowhead.com/spell=221713) |
| Priest | Holy | [Sol](http://www.wowhead.com/champion=872) | [222080](http://www.wowhead.com/spell=222080) |
| Priest | Shadow | [Zabra Hexx](http://www.wowhead.com/champion=870) | [222070](http://www.wowhead.com/spell=222070) |
| Rogue | Outcast | [Akama](http://www.wowhead.com/champion=718) | [222820](http://www.wowhead.com/spell=222820) |
| Rogue | Outcast | [Shade of Akama](http://www.wowhead.com/champion=719) | [222842](http://www.wowhead.com/spell=222842) |
| Rogue | Outlaw | [Vanessa VanCleef](http://www.wowhead.com/champion=591) | [221496](http://www.wowhead.com/spell=221496) |
| Shaman | Enhancement | [Rehgar Earthfury](http://www.wowhead.com/champion=612) | [217849](http://www.wowhead.com/spell=217849) |
| Shaman | Elemental | [Stormcaller Mylra](http://www.wowhead.com/champion=608) | [218154](http://www.wowhead.com/spell=218154) |
| Warlock | Destruction | [Ritssyn Flamescowl](http://www.wowhead.com/champion=589) | [216090](http://www.wowhead.com/spell=216090) |
| Warrior | Fury | [Dvalen Ironrune](http://www.wowhead.com/champion=714) | [222827](http://www.wowhead.com/spell=222827) |

**Comment by InvisiBilldotnet** [comment]
I found 20 [Legion Bodyguard spells on Wowhead](http://www.wowhead.com/spells/uncategorized/name:Bodyguard?filter=16;7;0).  The dumped SpellInfo is identical for all of them, other than the SpellID and icon values.  Wowhead does list all of them with both Alliance and Horde versions of name/class, but all of the bodyguards have the same info for both sides (not too unexpected, since we all share a Hall).

Here are the SpellID and icon values for each of them:
[Chen Stormstout - Brewmaster Monk](http://www.wowhead.com/champion=596)
[211945](http://www.wowhead.com/spell=211945)
611417

[The Monkey King - Windwalker Monk](http://www.wowhead.com/champion=602)
[212145](http://www.wowhead.com/spell=212145)
667301

[Ritssyn Flamescowl - Destruction Warlock](http://www.wowhead.com/champion=589)
[216090](http://www.wowhead.com/spell=216090)
236297

[Rehgar Earthfury - Enhancement Shaman](http://www.wowhead.com/champion=612)
[217849](http://www.wowhead.com/spell=217849)
538568

[Stormcaller Mylra - Elemental Shaman](http://www.wowhead.com/champion=608)
[218154](http://www.wowhead.com/spell=218154)
463562

[Broll Bearmantle - Feral Druid](http://www.wowhead.com/champion=641)
[218603](http://www.wowhead.com/spell=218603)
571585

[Addie Fizzlebog - Survival Hunter](http://www.wowhead.com/champion=746)
[219995](http://www.wowhead.com/spell=219995)
236445

[Archmage Modera - Frost Mage](http://www.wowhead.com/champion=717)
[220125](http://www.wowhead.com/spell=220125)
135865

[Millhouse Manastorm - Fire Mage](http://www.wowhead.com/champion=723)
[220212](http://www.wowhead.com/spell=220212)
135869

[Rexxar - Survival Hunter](http://www.wowhead.com/champion=743)
[220814](http://www.wowhead.com/spell=220814)
132409

[Vanessa VanCleef - Outlaw Rogue](http://www.wowhead.com/champion=591)
[221496](http://www.wowhead.com/spell=221496)
135358

[Vindicator Boros - Protection Paladin](http://www.wowhead.com/champion=479)
[221625](http://www.wowhead.com/spell=221625)
236256

[Arator the Redeemer - Retribution Paladin](http://www.wowhead.com/champion=758)
[221713](http://www.wowhead.com/spell=221713)
1360762

[Zabra Hexx - Shadow Priest](http://www.wowhead.com/champion=870)
[222070](http://www.wowhead.com/spell=222070)
1022950

[Sol - Holy Priest](http://www.wowhead.com/champion=872)
[222080](http://www.wowhead.com/spell=222080)
458225

[Koltira Deathweaver - Blood Death Knight](http://www.wowhead.com/champion=599)
[222365](http://www.wowhead.com/spell=222365)
135770

[Akama - Outcast](http://www.wowhead.com/champion=718)
[222820](http://www.wowhead.com/spell=222820)
1305151

[Dvalen Ironrune - Fury Warrior](http://www.wowhead.com/champion=714)
[222827](http://www.wowhead.com/spell=222827)
254108

[Shade of Akama - Outcast](http://www.wowhead.com/champion=719)
[222842](http://www.wowhead.com/spell=222842)
1305151

[Belath Dawnblade - Vengeance Demon Hunter](http://www.wowhead.com/champion=594)
[222964](http://www.wowhead.com/spell=222964)
1355117

When I dumped my follower info, it output so many lines I couldn't see my Bodyguard's entry.  If you have an addon that exposes IDs (like [idTip](https://mods.curse.com/addons/wow/spellid) or [Wowhead Link](https://mods.curse.com/addons/wow/wowhead-link)), you can simply [mouse over their Combat Ally ability icon on the Follower screen to get their Bodyguard SpellID](http://gaming.invisibill.net/wow/LegionBodyguardSpellID.png).

**Comment by Sharparam** [comment]
Thanks for the contribution, @InvisiBilldotnet! Do you by chance play on a non-English version of the WoW client? I need to find out if the return from `C_Garrison.GetFollowerStatus()` is localized. If you are, can you please run the following and tell me its output?

```
/dump C_Garrison.GetFollowerStatus(C_Garrison.GetFollowers(LE_FOLLOWER_TYPE_GARRISON_7_0)[1].followerID)
```

**Comment by InvisiBilldotnet** [comment]
Sorry, I'm en-US.  Hopefully someone can get that info.  According to [https://us.battle.net/support/en/article/changing-language](https://us.battle.net/support/en/article/changing-language), you can change the game's language in Battle.net, but I haven't tried it myself.

**Comment by Sharparam** [comment]
Bummer. It seems to work decently well at the moment at least. The health tracking is a little buggy when the bodyguard dies and respawns because there doesn't seem to be a good way to track that.

For English clients at least the current revision on `master` branch should work. And mousing over the bodyguard is a quick way to update its data (after it respawns for example).

Once I figure out the localization issue it should be ready for a new beta release of BGH.

**Comment by Sharparam** [comment]
@InvisiBilldotnet The latest alpha of LibBodyguard-1.0 and BodyguardHealth should now have preliminary support for Bodyguards. My testing so far has been promising, but more people testing it (with bodyguards other than Broll) is always positive!

Note that you'll have to install the alpha LibBodyguard-1.0 separately along with the alpha version of BodyguardHealth (both from Curse) in order to get the necessary alpha changes in LibBodyguard-1.0.
